### ISSUE TITLE
EASYME-md의 레포의 기본 설정 중 URL에 실제 서비스되고있는 URL을 넣어주세요

### ISSUE THREAD

**Issue by koremp** [EASYME-md/client#75]
왜냐면 제가 링크 찾느라 헷갈렸어요

**Comment by onealog** [comment]
안녕하세요. 확인이 늦어서 죄송합니다.   
실제 서비스되고 있는 URL 찾는 것에 어려움을 겪고 계신 것 같아서,   
카툰 이후에 나오는 제목에 링크를 걸었고, `사이트 바로 가기` 라는 텍스트도 추가하여 링크를 좀 더 잘 보일 수 있도록 했습니다.   
그리고 현재 도메인을 변경했는데요. 아직 서버 설정을 하지 않아서 저장이 되지 않는다는 점 참고 부탁드려요!

**Comment by koremp** [comment]
감사합니다.
뒤늦게 보니 이슈를 너무 대충 쓴 것 같아서 죄송하네요. 반영해주셔서 감사해요.
